#include "main.h"
struct Blueprint bps[] =
    {
        {
            .id = 1,
            .ore_robot_cost = {.ore = 4},
            .clay_robot_cost = {.ore = 4},
            .obsidian_robot_cost = {.ore = 4, .clay = 14},
            .geode_robot_cost = {.ore = 2, .obsidian = 16},
        },
        {
            .id = 2,
            .ore_robot_cost = {.ore = 2},
            .clay_robot_cost = {.ore = 2},
            .obsidian_robot_cost = {.ore = 2, .clay = 15},
            .geode_robot_cost = {.ore = 2, .obsidian = 7},
        },
        {
            .id = 3,
            .ore_robot_cost = {.ore = 4},
            .clay_robot_cost = {.ore = 3},
            .obsidian_robot_cost = {.ore = 2, .clay = 14},
            .geode_robot_cost = {.ore = 2, .obsidian = 7},
        },
        {
            .id = 4,
            .ore_robot_cost = {.ore = 4},
            .clay_robot_cost = {.ore = 3},
            .obsidian_robot_cost = {.ore = 2, .clay = 17},
            .geode_robot_cost = {.ore = 3, .obsidian = 16},
        },
        {
            .id = 5,
            .ore_robot_cost = {.ore = 2},
            .clay_robot_cost = {.ore = 2},
            .obsidian_robot_cost = {.ore = 2, .clay = 17},
            .geode_robot_cost = {.ore = 2, .obsidian = 10},
        },
        {
            .id = 6,
            .ore_robot_cost = {.ore = 3},
            .clay_robot_cost = {.ore = 3},
            .obsidian_robot_cost = {.ore = 3, .clay = 17},
            .geode_robot_cost = {.ore = 4, .obsidian = 8},
        },
        {
            .id = 7,
            .ore_robot_cost = {.ore = 4},
            .clay_robot_cost = {.ore = 4},
            .obsidian_robot_cost = {.ore = 4, .clay = 9},
            .geode_robot_cost = {.ore = 2, .obsidian = 20},
        },
        {
            .id = 8,
            .ore_robot_cost = {.ore = 3},
            .clay_robot_cost = {.ore = 4},
            .obsidian_robot_cost = {.ore = 3, .clay = 20},
            .geode_robot_cost = {.ore = 3, .obsidian = 14},
        },
        {
            .id = 9,
            .ore_robot_cost = {.ore = 3},
            .clay_robot_cost = {.ore = 3},
            .obsidian_robot_cost = {.ore = 2, .clay = 20},
            .geode_robot_cost = {.ore = 3, .obsidian = 18},
        },
        {
            .id = 10,
            .ore_robot_cost = {.ore = 4},
            .clay_robot_cost = {.ore = 4},
            .obsidian_robot_cost = {.ore = 2, .clay = 16},
            .geode_robot_cost = {.ore = 4, .obsidian = 16},
        },
        {
            .id = 11,
            .ore_robot_cost = {.ore = 4},
            .clay_robot_cost = {.ore = 4},
            .obsidian_robot_cost = {.ore = 4, .clay = 5},
            .geode_robot_cost = {.ore = 3, .obsidian = 15},
        },
        {
            .id = 12,
            .ore_robot_cost = {.ore = 2},
            .clay_robot_cost = {.ore = 3},
            .obsidian_robot_cost = {.ore = 2, .clay = 14},
            .geode_robot_cost = {.ore = 3, .obsidian = 8},
        },
        {
            .id = 13,
            .ore_robot_cost = {.ore = 2},
            .clay_robot_cost = {.ore = 4},
            .obsidian_robot_cost = {.ore = 2, .clay = 20},
            .geode_robot_cost = {.ore = 2, .obsidian = 17},
        },
        {
            .id = 14,
            .ore_robot_cost = {.ore = 4},
            .clay_robot_cost = {.ore = 3},
            .obsidian_robot_cost = {.ore = 2, .clay = 19},
            .geode_robot_cost = {.ore = 3, .obsidian = 10},
        },
        {
            .id = 15,
            .ore_robot_cost = {.ore = 4},
            .clay_robot_cost = {.ore = 4},
            .obsidian_robot_cost = {.ore = 4, .clay = 17},
            .geode_robot_cost = {.ore = 4, .obsidian = 20},
        },
        {
            .id = 16,
            .ore_robot_cost = {.ore = 2},
            .clay_robot_cost = {.ore = 3},
            .obsidian_robot_cost = {.ore = 2, .clay = 14},
            .geode_robot_cost = {.ore = 3, .obsidian = 20},
        },
        {
            .id = 17,
            .ore_robot_cost = {.ore = 4},
            .clay_robot_cost = {.ore = 4},
            .obsidian_robot_cost = {.ore = 2, .clay = 12},
            .geode_robot_cost = {.ore = 3, .obsidian = 15},
        },
        {
            .id = 18,
            .ore_robot_cost = {.ore = 4},
            .clay_robot_cost = {.ore = 3},
            .obsidian_robot_cost = {.ore = 2, .clay = 19},
            .geode_robot_cost = {.ore = 3, .obsidian = 13},
        },
        {
            .id = 19,
            .ore_robot_cost = {.ore = 2},
            .clay_robot_cost = {.ore = 3},
            .obsidian_robot_cost = {.ore = 3, .clay = 18},
            .geode_robot_cost = {.ore = 2, .obsidian = 19},
        },
        {
            .id = 20,
            .ore_robot_cost = {.ore = 2},
            .clay_robot_cost = {.ore = 4},
            .obsidian_robot_cost = {.ore = 2, .clay = 16},
            .geode_robot_cost = {.ore = 2, .obsidian = 9},
        },
        {
            .id = 21,
            .ore_robot_cost = {.ore = 3},
            .clay_robot_cost = {.ore = 3},
            .obsidian_robot_cost = {.ore = 2, .clay = 20},
            .geode_robot_cost = {.ore = 2, .obsidian = 20},
        },
        {
            .id = 22,
            .ore_robot_cost = {.ore = 3},
            .clay_robot_cost = {.ore = 3},
            .obsidian_robot_cost = {.ore = 3, .clay = 6},
            .geode_robot_cost = {.ore = 2, .obsidian = 16},
        },
        {
            .id = 23,
            .ore_robot_cost = {.ore = 3},
            .clay_robot_cost = {.ore = 4},
            .obsidian_robot_cost = {.ore = 3, .clay = 6},
            .geode_robot_cost = {.ore = 4, .obsidian = 11},
        },
        {
            .id = 24,
            .ore_robot_cost = {.ore = 4},
            .clay_robot_cost = {.ore = 4},
            .obsidian_robot_cost = {.ore = 4, .clay = 5},
            .geode_robot_cost = {.ore = 2, .obsidian = 10},
        },
        {
            .id = 25,
            .ore_robot_cost = {.ore = 3},
            .clay_robot_cost = {.ore = 4},
            .obsidian_robot_cost = {.ore = 2, .clay = 14},
            .geode_robot_cost = {.ore = 3, .obsidian = 14},
        },
        {
            .id = 26,
            .ore_robot_cost = {.ore = 3},
            .clay_robot_cost = {.ore = 4},
            .obsidian_robot_cost = {.ore = 3, .clay = 15},
            .geode_robot_cost = {.ore = 4, .obsidian = 16},
        },
        {
            .id = 27,
            .ore_robot_cost = {.ore = 4},
            .clay_robot_cost = {.ore = 3},
            .obsidian_robot_cost = {.ore = 4, .clay = 18},
            .geode_robot_cost = {.ore = 4, .obsidian = 11},
        },
        {
            .id = 28,
            .ore_robot_cost = {.ore = 4},
            .clay_robot_cost = {.ore = 3},
            .obsidian_robot_cost = {.ore = 3, .clay = 14},
            .geode_robot_cost = {.ore = 4, .obsidian = 17},
        },
        {
            .id = 29,
            .ore_robot_cost = {.ore = 2},
            .clay_robot_cost = {.ore = 3},
            .obsidian_robot_cost = {.ore = 3, .clay = 11},
            .geode_robot_cost = {.ore = 3, .obsidian = 14},
        },
        {
            .id = 30,
            .ore_robot_cost = {.ore = 4},
            .clay_robot_cost = {.ore = 4},
            .obsidian_robot_cost = {.ore = 4, .clay = 8},
            .geode_robot_cost = {.ore = 4, .obsidian = 14},
        },
};
#define NUM_BPS 30
